name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "ikaroshub"
          password: ${{ secrets.IKRS_DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ikaroshub/dbt-sqlserver:latest .
          docker push ikaroshub/dbt-sqlserver:latest